### ISSUE TITLE
pace_neutrons --jupyter command now working

### ISSUE THREAD

**Issue by a-larkins99** [pace-neutrons/pace-python#34]
Having installed jupyter on windows via `pip install jupyter` and being able to launch regularly by running `jupyter notebook` , I have found that `pace_neutrons --jupter` does not work currently. I receive the following error:

Traceback (most recent call last):
  File "C:\Users\oms84157\AppData\Local\mambaforge\envs\test_cli\lib\site-packages\pace_neutrons_cli\cli.py", line 107, in main
    import notebook.notebookapp
ModuleNotFoundError: No module named 'notebook.notebookapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\oms84157\AppData\Local\mambaforge\envs\test_cli\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\oms84157\AppData\Local\mambaforge\envs\test_cli\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\oms84157\AppData\Local\mambaforge\envs\test_cli\Scripts\pace_neutrons.exe\__main__.py", line 7, in <module>
  File "C:\Users\oms84157\AppData\Local\mambaforge\envs\test_cli\lib\site-packages\pace_neutrons_cli\cli.py", line 109, in main
    raise RuntimeError('Jupyter notebook is not installed')
RuntimeError: Jupyter notebook is not installed

**Comment by mducle** [comment]
Checked, not working on Jupyter `7.2.2`
